# render.yaml - DIAGNOSTIC VERSION

services:
  - type: web
    name: yeab-game-zone-api
    env: python
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    # This start command will just list files and sleep.
    # It cannot fail unless the whole environment is broken.
    startCommand: "echo '--- Starting Diagnostic ---'; ls -R; echo '--- Diagnostic Finished ---'; while true; do sleep 300; done"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12