# render.yaml - FINAL VERSION

services:
  - type: web
    name: yeab-game-zone-api
    env: python
    plan: starter
    buildCommand: "pip install -r requirements.txt && python main.py initdb"
    startCommand: "gunicorn -w 4 -k uvicorn.workers.UvicornWorker api.main:app"
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: yeab-ludo-db
          property: connectionString
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: CHAPA_API_KEY
        sync: false
      - key: WEBHOOK_URL
        fromService:
          type: web
          name: yeab-game-zone-api
          property: url

  - type: pserv
    name: yeab-ludo-db
    databaseName: yeab_game_db
    databaseUser: yeab_user
    plan: free

  - type: worker
    name: yeab-game-forfeit-worker
    env: python
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "while true; do echo 'Worker is alive...'; sleep 300; done"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: yeab-ludo-db
          property: connectionString
      - key: TELEGRAM_BOT_TOKEN
        sync: false