# render.yaml
services:
  - type: web
    name: yeab-game-zone-api
    env: python
    plan: starter # Use a paid plan for production to prevent sleeping
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -k uvicorn.workers.UvicornWorker api.main:app"
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: yeab-ludo-db
          property: connectionString
      - key: TELEGRAM_BOT_TOKEN
        sync: false # Set this in the Render dashboard secrets
      - key: CHAPA_API_KEY
        sync: false # Set this in the Render dashboard secrets
      - key: WEBHOOK_URL
        fromService:
          type: web
          name: yeab-game-zone-api
          property: url

  - type: pserv # Private Service (Database)
    name: yeab-ludo-db
    databaseName: yeab_game_db
    databaseUser: yeab_user
    plan: free # Use a paid plan for production

  - type: worker
    name: yeab-game-forfeit-worker
    env: python
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py forfeit_worker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: yeab-ludo-db
          property: connectionString
      - key: TELEGRAM_BOT_TOKEN
        sync: false